#spring:
#  thymeleaf:
#    mode: HTML5
#    encoding: utf-8
#    servlet:
#      content-type: text/html
#    suffix: .html
#    cache: false
#    cahche:
#      chain:
#        strategy:
#          content:
#            enabled: true
#            paths: /**
#    prefix: classpath:/templates/
#
#server:
#  port: 8082
#  servlet:
#    context-path: /qiaofeng